# Site settings
description:  A blog about programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mateusjatenee.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mateusjatenee
user_description: Software Developer at Weenside
user_title: Web Developer
email: mateus.jatene@gmail.com
twitter_username: mateusjatenee
github_username:  mateusjatenee
gplus_username:  mateusjatenee
disqus_username: mateusjatenee

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
